backend:
  name: git-gateway
  branch: main  # The branch to update
  repo: mandrewsstudio/astro  # Your GitHub repository

media_folder: "public/uploads"  # Folder to store media
public_folder: "/uploads"  # Public URL for media

collections:
  - name: "home"  # Name of the collection
    label: "Home"  # Label for the admin UI
    folder: "public/content/home"  # Folder where posts are stored
    create: true  # Allow new posts to be created
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # Post slug format
    fields:  # The fields for each document
      - { name: "layout", label: "Layout", widget: "hidden", default: "posts" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "dateformat" }
      - { name: "thumbnail", label: "Featured Image", widget: "image" }
      - { name: "body", label: "Body", widget: "markdown" }
