backend:
  name: git-gateway
  branch: main  # The branch to update
  repo: mandrewsstudio/astro  # Your GitHub repository

media_folder: "public/uploads"  # Folder to store media
public_folder: "/uploads"  # Public URL for media

collections:
  - name: "home"  # Name of the collection
    label: "Home"  # Label for the admin UI
    folder: "public/content/home"  # Folder where posts are stored
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
